language: php

php:
  - '7.0'

before_script:
  - "java -version"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - "wget -O selenium.jar http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar"
  - "make startserver"
  - "make startselenium"
  - sleep 10

install:
  - "composer install"

script:
  - "make phpunit"

after_script:
  - "make stopselenium"
  - "make stopserver"
